import Link from "next/link";
import { gamesService } from "@/app/games/service";

export const dynamic = "force-dynamic";

export default async function NewGamePage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams;
  const results = q ? await gamesService.searchExternalGames({ query: q }) : null;
  return <main className="mx-auto min-h-screen max-w-2xl px-4 py-8 sm:px-6"><div className="mb-8 flex items-center gap-3"><Link href="/" className="text-sm text-slate-600">← 收藏庫</Link><h1 className="text-3xl font-semibold">新增遊戲</h1></div><form className="flex gap-2"><label className="sr-only" htmlFor="game-query">搜尋遊戲</label><input id="game-query" name="q" defaultValue={q} placeholder="輸入遊戲名稱" className="min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-4 py-3" /><button className="rounded-xl bg-emerald-900 px-4 py-3 font-semibold text-white" type="submit">同時搜尋</button></form><section className="mt-8 space-y-6" aria-live="polite">{results?.groups.map((group) => <div key={group.provider}><div className="mb-2 flex items-center justify-between"><h2 className="text-lg font-semibold">{group.provider === "bgg" ? "BoardGameGeek 桌遊" : "IGDB 電子遊戲"}</h2>{group.errorCode && <p className="text-sm text-amber-800">此來源暫時無法使用（{group.errorCode}）</p>}</div>{group.items.length === 0 ? <p className="rounded-xl bg-white/60 p-4 text-sm text-slate-600">沒有找到結果。</p> : <ul className="space-y-2">{group.items.map((item) => <li key={`${item.ref.provider}:${item.ref.sourceId}`} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4"><span><strong>{item.title}</strong>{item.releaseYear && <span className="ml-2 text-sm text-slate-500">{item.releaseYear}</span>}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">展開確認</span></li>)}</ul>}</div>)}</section><details className="mt-8 rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer font-semibold">找不到？建立手動條目</summary><form className="mt-4 space-y-3"><input name="manualName" placeholder="遊戲名稱" className="w-full rounded-xl border border-slate-300 px-4 py-3" /><select name="medium" className="w-full rounded-xl border border-slate-300 px-4 py-3" defaultValue="board_game"><option value="board_game">桌遊</option><option value="video_game">電子遊戲</option></select><button className="w-full rounded-xl bg-emerald-900 px-4 py-3 font-semibold text-white" type="submit">建立手動條目</button></form></details></main>;
}
